const hre = require("hardhat");
const fs = require("fs");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Balance:", hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)), "OPN");

  // 1. Deploy OracleKeeper
  console.log("\n[1/3] Deploying OracleKeeper...");
  const OracleKeeper = await hre.ethers.getContractFactory("OracleKeeper");
  // Initial price: $0.05 = 50000 (price stored as 6 decimal USD, e.g. 50000 = $0.050000)
  const oracle = await OracleKeeper.deploy(50000);
  await oracle.waitForDeployment();
  const oracleAddress = await oracle.getAddress();
  console.log("OracleKeeper deployed:", oracleAddress);

  // 2. Deploy LiquidityVault
  console.log("\n[2/3] Deploying LiquidityVault...");
  const LiquidityVault = await hre.ethers.getContractFactory("LiquidityVault");
  const vault = await LiquidityVault.deploy();
  await vault.waitForDeployment();
  const vaultAddress = await vault.getAddress();
  console.log("LiquidityVault deployed:", vaultAddress);

  // 3. Deploy PerpEngine
  console.log("\n[3/3] Deploying PerpEngine...");
  const PerpEngine = await hre.ethers.getContractFactory("PerpEngine");
  const perp = await PerpEngine.deploy(oracleAddress, vaultAddress);
  await perp.waitForDeployment();
  const perpAddress = await perp.getAddress();
  console.log("PerpEngine deployed:", perpAddress);

  // 4. Wire up: set PerpEngine on LiquidityVault
  console.log("\nWiring contracts...");
  const tx = await vault.setPerpEngine(perpAddress);
  await tx.wait();
  console.log("PerpEngine set on LiquidityVault ✓");

  // 5. Save addresses
  const addresses = {
    network: hre.network.name,
    chainId: 984,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    contracts: {
      OracleKeeper: oracleAddress,
      LiquidityVault: vaultAddress,
      PerpEngine: perpAddress
    }
  };

  fs.writeFileSync("./deployed-addresses.json", JSON.stringify(addresses, null, 2));
  console.log("\nAddresses saved to deployed-addresses.json");

  // Also write to frontend config
  const frontendConfig = `// Auto-generated by deploy script
export const DEPLOYED_ADDRESSES = ${JSON.stringify(addresses.contracts, null, 2)};
export const CHAIN_ID = 984;
export const RPC_URL = "https://testnet-rpc.iopn.tech";
`;
  fs.writeFileSync("./frontend/src/utils/addresses.js", frontendConfig);
  console.log("Frontend config updated ✓");

  console.log("\n=============================");
  console.log("DEPLOYMENT COMPLETE");
  console.log("=============================");
  console.log("OracleKeeper:", oracleAddress);
  console.log("LiquidityVault:", vaultAddress);
  console.log("PerpEngine:", perpAddress);
  console.log("\nNext steps:");
  console.log("1. Update keeper/.env with ORACLE_ADDRESS=" + oracleAddress);
  console.log("2. cd keeper && node keeper.js");
  console.log("3. cd frontend && npm run dev");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
