// Auto-generated by deploy script
export const DEPLOYED_ADDRESSES = {
  "OracleKeeper": "0x688428b07903c792AF70994Fd4C11Cd0eB33E76D",
  "LiquidityVault": "0xE73b20FDD21E23EFd861baf5a5f88775E3695969",
  "PerpEngine": "0x4a7acf3Bba2A15d5493f7C772C96d2e28b5C9836"
};
export const CHAIN_ID = 984;
export const RPC_URL = "https://testnet-rpc.iopn.tech";
