// Auto-generated by deploy.js — update DEPLOYED_ADDRESSES after deployment
export const DEPLOYED_ADDRESSES = {
  OracleKeeper: "0x688428b07903c792AF70994Fd4C11Cd0eB33E76D",
  LiquidityVault: "0xE73b20FDD21E23EFd861baf5a5f88775E3695969",
  PerpEngine: "0x4a7acf3Bba2A15d5493f7C772C96d2e28b5C9836"
};

export const CHAIN_ID = 984;
export const CHAIN_NAME = "OPN Testnet";
export const RPC_URL = "https://testnet-rpc.iopn.tech";
export const EXPLORER_URL = "https://explorer.testnet.iopn.tech";
export const CURRENCY = { name: "OPN", symbol: "OPN", decimals: 18 };

export const ORACLE_ABI = [
  "function getPrice() external view returns (uint256)",
  "function getPriceHistory() external view returns (uint256[50] memory prices, uint256[50] memory timestamps, uint256 count)",
  "function lastUpdated() external view returns (uint256)",
  "function isPriceStale() external view returns (bool)",
  "event PriceUpdated(uint256 price, uint256 timestamp)"
];

export const VAULT_ABI = [
  "function deposit() external payable",
  "function withdraw(uint256 _shares) external",
  "function getVaultBalance() external view returns (uint256 total, uint256 reserved, uint256 available)",
  "function getLPShare(address _lp) external view returns (uint256 shares, uint256 value)",
  "function totalShares() external view returns (uint256)",
  "event Deposited(address indexed lp, uint256 amount, uint256 shares)",
  "event Withdrawn(address indexed lp, uint256 amount, uint256 shares)"
];

export const PERP_ABI = [
  "function openLong(uint8 _leverage) external payable",
  "function openShort(uint8 _leverage) external payable",
  "function closePosition(uint256 _positionId) external",
  "function liquidate(uint256 _positionId) external",
  "function getPosition(uint256 _positionId) external view returns (tuple(address trader, uint256 collateral, uint8 leverage, uint256 positionSize, uint256 entryPrice, uint256 liquidationPrice, bool isLong, bool isOpen, uint256 openedAt))",
  "function getTraderPositions(address _trader) external view returns (uint256[])",
  "function getHealthFactor(uint256 _positionId) external view returns (uint256)",
  "function getOpenPositionPnL(uint256 _positionId) external view returns (int256)",
  "function getLeaderboard() external view returns (address[], int256[])",
  "function realizedPnL(address) external view returns (int256)",
  "function isLiquidatable(uint256 _positionId) external view returns (bool)",
  "event PositionOpened(uint256 indexed positionId, address indexed trader, bool isLong, uint256 collateral, uint8 leverage, uint256 entryPrice, uint256 liquidationPrice, uint256 positionSize)",
  "event PositionClosed(uint256 indexed positionId, address indexed trader, uint256 exitPrice, int256 pnl, uint256 collateralReturned)",
  "event Liquidated(uint256 indexed positionId, address indexed trader, address indexed liquidator, uint256 price, uint256 liquidatorBonus)"
];
